#--------------------------------------------------------------
#                 Makefile for ltmp module
#--------------------------------------------------------------

# List module object filenames
ltmp_objects=\
absorption_profile.o \
data.o \
field.o \
initialise.o \
interface.o \
is_enabled.o \
local_temperature_gradient.o \
local_temperature_pulse.o \
output.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/ltmp/,$(ltmp_objects))
