#--------------------------------------------------------------
#                 Makefile for grains module
#--------------------------------------------------------------

# List module object filenames
grains_objects=\
data.o \
grain_assign.o \
grain_elliptical_rounding.o \
grain_geometry.o \
grain_packing.o \
grain_seeds.o \
grain_shape.o \
grain_substructure.o \
grain_tessellation.o \
granular_film.o \
initialize.o \
interface.o \
progress_indicator.o \
properties.o \
voronoi_grain_rounding.o \
write_grain_vertices.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/grains/,$(grains_objects))
