#--------------------------------------------------------------
#          Makefile for environment module
#--------------------------------------------------------------

# List module object filenames
environment_objects =\
data.o \
initialize.o \
interface.o \
calculate_chi_perp.o \
calculate_chi_para.o \
LLB.o \
fieldsLLB.o \
output.o \
shields.o \
demag.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/environment/,$(environment_objects))
