#--------------------------------------------------------------
#          Makefile for spintextures module
#--------------------------------------------------------------

# List module object filenames
spintextures_objects =\
data.o \
initialize.o \
interface.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/spintextures/,$(spintextures_objects))
