#--------------------------------------------------------------
#          Makefile for dipole module
#--------------------------------------------------------------

# List module object filenames
dipole_objects =\
mpi.o \
data.o \
initialize.o \
interface.o \
update.o \
field.o 

# Append module objects to global tree
OBJECTS+=$(addprefix obj/dipole/,$(dipole_objects))
