#--------------------------------------------------------------
#          Makefile for anisotropy module
#--------------------------------------------------------------

# List module object filenames
anisotropy_objects =\
data.o \
initialise.o \
interface.o \
secondorder.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/anisotropy/,$(anisotropy_objects))
