#--------------------------------------------------------------
#          Makefile for anisotropy module
#--------------------------------------------------------------

# List module object filenames
anisotropy_objects =\
data.o \
fields.o \
initialize.o \
interface.o \
lattice.o \
uniaxial_second_order.o \
uniaxial_fourth_order.o \
cubic_fourth_order.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/anisotropy/,$(anisotropy_objects))
