#--------------------------------------------------------------
#          Makefile for spinpumping module
#--------------------------------------------------------------

# List module object filenames
spinpumping_objects =\
cells_magnetization.o \
data.o \
get_old_spin_array.o \
initialize.o \
interface.o \
output_atomistic_spin_pumping.o \
spin_pumping.o \
update.o 

# Append module objects to global tree
OBJECTS+=$(addprefix obj/spinpumping/,$(spinpumping_objects))
