#--------------------------------------------------------------
#          Makefile for spintransport module
#--------------------------------------------------------------

# List module object filenames
spintransport_objects =\
data.o \
field.o \
initialize.o \
interface.o \
magnetization.o \
resistance.o \
update.o \
voltage.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/spintransport/,$(spintransport_objects))
