#--------------------------------------------------------------
#          Makefile for unitcell module
#--------------------------------------------------------------

# List module object filenames
unitcell_objects =\
data.o \
exchange.o \
initialize.o \
interactions.o \
interface.o \
normalise.o \
read.o \
read_interactions.o \
set_exchange_type.o \
shells.o \
sc.o \
bcc.o \
bcc110.o \
fcc.o \
hcp.o \
heusler.o \
honeycomb.o \
honeycomb-a.o \
kagome.o \
rocksalt.o \
rutile.o \
spinel.o \
spinel-layered.o \
NdFeB.o\
SmFeN.o\
verify.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/unitcell/,$(unitcell_objects))
