#--------------------------------------------------------------
#          Makefile for unitcell module
#--------------------------------------------------------------

# List module object filenames
unitcell_objects =\
data.o \
exchange.o \
initialize.o \
interactions.o \
interface.o \
normalise.o \
read.o \
read_interactions.o \
set_exchange_type.o \
sc.o \
bcc.o \
fcc.o \
hcp.o \
rocksalt.o \
verify.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/unitcell/,$(unitcell_objects))
