#--------------------------------------------------------------
#                 Makefile for statistics module
#--------------------------------------------------------------

# List module object filenames
statistics_objects=\
data.o \
energy.o \
initialize.o \
interface.o \
magnetization.o \
specific_heat.o \
standard_deviation.o\
reset.o \
susceptibility.o \
binder_cumulant.o\
torque.o \
update.o \
spin_length.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/statistics/,$(statistics_objects))
