#--------------------------------------------------------------
#                 Makefile for statistics module
#--------------------------------------------------------------

# List module object filenames
statistics_objects=\
data.o \
energy.o \
initialize.o \
interface.o \
magnetization.o \
specific_heat.o \
standard_deviation.o\
statistics.o \
susceptibility.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/statistics/,$(statistics_objects))
