#--------------------------------------------------------------
#          Makefile for exchange module
#--------------------------------------------------------------

# List module object filenames
exchange_objects =\
data.o \
initialize.o \
interface.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/exchange/,$(exchange_objects))
