#--------------------------------------------------------------
#          Makefile for exchange module
#--------------------------------------------------------------

# List module object filenames
exchange_objects =\
biquadratic_fields.o \
data.o \
dmi.o \
energy.o \
exchange_fields.o \
fields.o \
get_exchange_type.o \
initialize.o \
initialize_biquadratic.o \
interface.o \
set_biquadratic_exchange_type.o \
set_exchange_type.o \
unroll_normalised.o \
unroll_normalised_biquadratic.o \
unroll.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/exchange/,$(exchange_objects))
