#--------------------------------------------------------------
#          Makefile for exchange module
#--------------------------------------------------------------

# List module object filenames
exchange_objects =\
data.o \
dmi.o \
energy.o \
fields.o \
get_exchange_type.o \
initialize.o \
interface.o \
set_exchange_type.o \
unroll_normalised.o \
unroll.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/exchange/,$(exchange_objects))
