#--------------------------------------------------------------
#                 Makefile for ltmp module
#--------------------------------------------------------------

# List module object filenames
spintorque_objects=\
data.o \
field.o \
initialise.o \
interface.o \
magnetization.o \
matrix.o \
output.o \
spinaccumulation.o \


# Append module objects to global tree
OBJECTS+=$(addprefix obj/spintorque/,$(spintorque_objects))