#--------------------------------------------------------------
#                 Makefile for statistics module
#--------------------------------------------------------------

# List module object filenames
constants_objects=\
constants.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/constants/,$(constants_objects))
