#--------------------------------------------------------------
#          Makefile for quantum module
#--------------------------------------------------------------

# List module object filenames
quantum_objects =\
data.o \
initialize.o \
interface.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/quantum/,$(quantum_objects))
