#--------------------------------------------------------------
#          Makefile for spininitialize module
#--------------------------------------------------------------

# List module object filenames
spininitialize_objects =\
data.o \
initialize.o \
interface.o \
parse.o \
textures.o \
vector_field.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/spininitialize/,$(spininitialize_objects))
