#--------------------------------------------------------------
#          Makefile for montecarlo module
#--------------------------------------------------------------

# List module object filenames
montecarlo_objects =\
data.o \
initialize.o \
interface.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/montecarlo/,$(montecarlo_objects))
