#--------------------------------------------------------------
#          Makefile for config module
#--------------------------------------------------------------

# List module object filenames
config_objects =\
atoms_spins.o \
buffer.o \
config.o \
data.o \
initialize.o \
interface.o \
meta.o \
output_legacy.o \
write.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/config/,$(config_objects))
