#--------------------------------------------------------------
#          Makefile for config module
#--------------------------------------------------------------

# List module object filenames
config_objects =\
initialize.o \
interface.o \
output.o \
output_legacy.o \
config.o \
data.o \
write.o \
meta.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/config/,$(config_objects))
