#--------------------------------------------------------------
#          Makefile for config module
#--------------------------------------------------------------

# List module object filenames
config_objects =\
data.o \
initialize.o \
interface.o \
output.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/config/,$(config_objects))
