#--------------------------------------------------------------
#          Makefile for vio module
#--------------------------------------------------------------

# List module object filenames
vio_objects =\
check.o \
data.o \
datalog.o \
globalio.o \
initialize.o \
interface.o \
match.o \
outputfunctions.o \
read.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/vio/,$(vio_objects))
