#--------------------------------------------------------------
#          Makefile for vio module
#--------------------------------------------------------------

# List module object filenames
vio_objects =\
check.o \
data.o \
datalog.o \
get_string.o \
globalio.o \
grain.o \
initialize.o \
interface.o \
match.o \
match_grain_list.o \
nullify.o \
outputfunctions.o \
read.o \
string_to_x.o \
timestamp.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/vio/,$(vio_objects))
