#--------------------------------------------------------------
#          Makefile for cells module
#--------------------------------------------------------------

# List module object filenames
cells_objects =\
data.o \
initialize.o \
interface.o \
mag.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/cells/,$(cells_objects))
