#--------------------------------------------------------------
#          Makefile for neighbours module
#--------------------------------------------------------------

# List module object filenames
neighbours_objects =\
clear.o \
generate.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/neighbours/,$(neighbours_objects))
