#--------------------------------------------------------------
#                 Makefile for create module
#--------------------------------------------------------------

# List module object filenames
create_objects=\
agglomorate.o \
alloy.o \
bubble.o \
bulk.o \
centre_particle.o \
cone.o \
compare_radius.o \
composition.o \
create.o \
cs_set_atom_vars2.o \
cube.o \
cylinder.o \
data.o \
ellipse.o \
ellipsoid.o \
faceted.o \
generate_crystal.o \
geometry.o \
get_material_height.o \
hexagonal_array.o \
initialize.o \
interface.o \
layers.o \
multilayers.o \
mpi.o \
particle.o \
roughness.o \
sort_atoms_by_grain.o \
sphere.o \
sphere_size.o \
square_array.o \
system_type.o \
teardrop.o \
truncated_octahedron.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/create/,$(create_objects))
