#--------------------------------------------------------------
#                 Makefile for sim module
#--------------------------------------------------------------

# List module object filenames
sim_objects=\
data.o \
initialize.o \
interface.o \
llg_quantum.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/simulate/,$(sim_objects))
