#--------------------------------------------------------------
#                 Makefile for sim module
#--------------------------------------------------------------

# List module object filenames
sim_objects=\
data.o \
increment_time.o \
initialize.o \
initialize_modules.o \
interface.o \
llg_quantum.o \
LSF.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/simulate/,$(sim_objects))
