#--------------------------------------------------------------
#          Makefile for hierarchical module
#--------------------------------------------------------------

# List module object filenames
hierarchical_objects =\
corners.o \
data.o \
initialize.o \
intra.o \
inter.o \
interface.o \
mag.o \
update.o
# Append module objects to global tree
OBJECTS+=$(addprefix obj/hierarchical/,$(hierarchical_objects))
