#--------------------------------------------------------------
#          Makefile for sld module
#--------------------------------------------------------------

# List module object filenames
sld_objects =\
data.o \
initialize.o \
interface.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/sld/,$(sld_objects))
