#------------------------------------------------------------------
#          Makefile for hamr module
#--------------------------------------------------------------

# List module object filenames
hamr_objects =\
bit_sequence.o \
data.o \
fields.o \
field_profiles.o \
get_hamr_variables.o \
hamr_continuous.o \
initialize.o \
interface.o \
temp_profiles.o



# Append module objects to global tree
OBJECTS+=$(addprefix obj/hamr/,$(hamr_objects))
