#--------------------------------------------------------------
#                 Makefile for gpu module
#--------------------------------------------------------------

# List module object filenames
gpu_objects=\
config.o \
data.o \
finalize.o \
initialize.o \
interface.o \
llg_heun.o \
monte_carlo.o \
statistics.o \
transfer.o \
update.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/gpu/,$(gpu_objects))
