#--------------------------------------------------------------
#                 Makefile for gpu module
#--------------------------------------------------------------

# List module object filenames
gpu_objects=\
data.o \
finalize.o \
initialize.o \
llg_heun.o \
statistics.o

# Append module objects to global tree
OBJECTS+=$(addprefix obj/gpu/,$(gpu_objects))
